TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw.oera.no/security-token-service
PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api

NORG2_API_V1_URL: https://api-gw.oera.no/norg2/api/v1

EREG_URL: https://api-gw.oera.no/ereg/api

AXSYS_URL: https://api-gw.oera.no/axsys/api/v2
AXSYS_CLUSTER: prod-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

KABAL_OPPGAVESTYRING_EGEN_ENHET: e9de217a-7244-45ac-8a06-1994905d7964
FORTROLIG: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
STRENGT_FORTROLIG: ad7b87a6-9180-467c-affc-20a566b0fec0
EGEN_ANSATT: e750ceb5-b70b-4d94-b4fa-9d22467b786b

KABAL_ADMIN: cd78b8e8-73a3-4fb6-8234-7bebb5e5b9e9
