TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw-q1.oera.no/security-token-service
PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api

NORG2_API_V1_URL: https://api-gw-q1.oera.no/norg2/api/v1
PROXY_APP_CLIENT_ID: c6050231-3b9f-4173-8d1e-39b7e6e3392e

EREG_URL: https://api-gw-q1.oera.no/ereg/api

AXSYS_URL: https://api-gw-q1.oera.no/axsys/api/v2
AXSYS_CLUSTER: dev-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

KABAL_OPPGAVESTYRING_EGEN_ENHET: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002

KABAL_ADMIN: 011af9b0-792d-4d2c-a2eb-9a59fc095002
