SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: igroup
SERVICE_USER_PASSWORD: itest
SLACK_URL: localhost:8080
SLACK_CHANNEL_ID: #none
NAIS_CLUSTER_NAME: local
AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
NORG2_API_V1_URL: local
NORG2_APIKEY: 123
OPPGAVE_APIKEY: 456
STS_APIKEY: 789
PDL_BASE_URL: local
PDL_APIKEY: 159
AXSYS_APIKEY: 357
nais:
  cluster:
    name: local
OPEN_SEARCH_USERNAME: whatever
OPEN_SEARCH_PASSWORD: password
OPEN_SEARCH_URI: "http://localhost:9200"

AXSYS_URL: https://axsys.dev.adeo.no/v1

KABAL_OPPGAVESTYRING_EGEN_ENHET: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002
