spring:
  application:
    name: kabal-search
  main:
    banner-mode: OFF
  sleuth:
    baggage:
      remote-fields:
        - Nav-Callid
        - Nav-Consumer-Id
      correlation-fields:
        - Nav-Callid
        - Nav-Consumer-Id
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 7081
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    jolokia:
      config:
        - debug: true
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus, jolokia
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

SERVICE_USER_USERNAME: srvklage-saksbeh

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      azure-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      pdl-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${PDL_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      pdl-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${PDL_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      axsys-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${AXSYS_CLUSTER}.${AXSYS_NAMESPACE}.${AXSYS_APP}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      kabal-innstillinger-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${NAIS_CLUSTER_NAME}.${NAIS_NAMESPACE}.${KABAL_INNSTILLINGER_APP_NAME}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      axsys-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${AXSYS_CLUSTER}.${AXSYS_NAMESPACE}.${AXSYS_APP}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      app:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

navCallId: Nav-Callid
navConsumerId: Nav-Consumer-Id

MICROSOFT_GRAPH_URL: https://graph.microsoft.com/v1.0
UNLEASH_URL: https://unleash.nais.io/api/

EGENANSATT_KAFKA_TOPIC: nom.skjermede-personer-v1
PDL_PERSON_KAFKA_TOPIC: aapen-person-pdl-dokument-v1
BEHANDLING_ENDRET_KAFKA_TOPIC_V2: klage.behandling-endret.v2

SERVICE_USER_PASSWORD: itest

KABAL_INNSTILLINGER_BASE_URL: http://kabal-innstillinger
KABAL_INNSTILLINGER_APP_NAME: kabal-innstillinger
