TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw.oera.no/security-token-service
PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api

NORG2_API_V1_URL: https://api-gw.oera.no/norg2/api/v1

EREG_URL: https://api-gw.oera.no/ereg/api

AXSYS_URL: https://api-gw.oera.no/axsys/api/v2
AXSYS_CLUSTER: prod-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

KABAL_OPPGAVESTYRING_EGEN_ENHET: e9de217a-7244-45ac-8a06-1994905d7964
FORTROLIG: 94f37fa2-94c9-49f7-b4df-e6be7c0d1082
STRENGT_FORTROLIG: ac0f28e8-115e-4972-b063-162366bb9399
EGEN_ANSATT: b14cf640-30bc-4420-b34c-26488c15e71e

KABAL_ADMIN: cd78b8e8-73a3-4fb6-8234-7bebb5e5b9e9
