ingresses:
  - https://kabal-search.dev.intern.nav.no
externalHosts:
  - host: login.microsoftonline.com
  - host: hooks.slack.com
  - host: unleash.nais.io
  - host: klage-fss-proxy.dev-fss-pub.nais.io
  - host: kafka-schema-registry.nais-q.adeo.no
  - host: pdl-api.dev-fss-pub.nais.io
    ports:
      - name: https
        port: 26482
        protocol: TCP
springProfile: dev-gcp
tenant: trygdeetaten.no
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
k9_cluster: dev-fss
kafka_pool: nav-dev

KABAL_OPPGAVESTYRING_EGEN_ENHET: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002

envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx4096m"