apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kabal-search
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  image: {{ image }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      claims:
        groups:
        {{#each adRoles}}
          - id: {{value }}
        {{/each}}
        extra:
          - NAVident
  openSearch:
    access: admin
    instance: oppgaver
  kafka:
    pool: {{kafka_pool}}
  port: 7081
  startup:
    failureThreshold: 10
    initialDelay: 10
    path: /internal/health
    periodSeconds: 5
    timeout: 2
  liveness:
    path: /internal/health
    timeout: 3
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /internal/health
    timeout: 3
    periodSeconds: 5
    failureThreshold: 3
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 50m
      memory: 1024Mi
  ingresses:
  {{#each ingresses as |ingress|}}
    - {{ingress}}
  {{/each}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: kabal-frontend
        - application: kabal-api
    outbound:
      rules:
        - application: kabal-api
        - application: kabal-innstillinger
        - application: logging
          namespace: nais-system
      external:
      {{#each externalHosts}}
        - host: {{host}}
      {{/each}}
  envFrom:
    - secret: srvklage-saksbeh
    - secret: slack-url
    - secret: slack-channel-id
    - secret: elastic
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
  {{#each envs}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
  {{#each adRoles}}
    - name: {{name}}
      value: {{value}}
  {{/each}}